number_vec = ["one", "two", "three"]

# Bad style:
for (index, text) in enumerate(number_vec)
    println("index $index text $text number_vec $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia
    println("index ", index, " text ", text, " number_vec ", number_vec[index])
end

for index in eachindex(number_vec)
    println("index $index text $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia
end

for index in range(1:length(number_vec))
    println("index $index text $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia
end

for index in 1:length(number_vec)
    println("index $index text $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia
end

# This is OK
index = 2
while index <= 10
    println("$index")
    index += 2
end
