
for (index, text) in enumerate(number_vec)
    println("index $index text $text number_vec $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia
    # In future we should do this thing below
    # println("index ", index, " text ", text, " number_vec ", number_vec[index])
end

number_vec = ["one", "two", "three"]
# for index in eachindex(number_vec)
#     println("index $index text $(number_vec[index])")
#     index = 1 # Don't change the index generated by Julia
# end

for index in range(1:length(number_vec))
    # println("index $index text $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia
end

"""
This is function doathing. This doc comment should not be flagged,
because it is okay to have code in doc comments. The signature is:

    doathing()
"""
function doathing()
    for index in eachindex(number_vec)
    #= println("index $index text $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia =#
    end
end


for index in 1:length(number_vec)
    println("index $index text $(number_vec[index])")
    index = 1 # Don't change the index generated by Julia
end

# This is OK
index = 2
while index <= 10
    println("$index")
    index += 2
end
